// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

namespace WebApp_MVC_Animales.Models.ViewModels
{
    public class AnimalViewModel
    {
        public List<Animal> Animales { get; set; } = new List<Animal>();

        public List<TipoAnimal> TipoAnimales { get; set; } = new List<TipoAnimal>();


        /*public List<string> Animales { get; set; } = new List<string>();

         public AnimalesViewModel()
         {
             Animales = new List<string> {
             "Elefante",
             "Tigre",
             "León",
             "Jirafa",
             "Rinoceronte",
             "Oso Panda",
             "Koala",
             "Cephalopodo",
             "Canguro",
             "Águila",
         };
         }*/
    }

}
