// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebApp_MVC_Animales.Models;

public partial class AnimalsContext : DbContext
{
    public AnimalsContext() { }

    public AnimalsContext(DbContextOptions<AnimalsContext> options) : base(options) { }

    public virtual DbSet<Animal> Animals { get; set; }

    public virtual DbSet<TipoAnimal> TipoAnimals { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Data Source=46.183.118.102,54321;" +
            "Initial Catalog=CarmenAnimales;" +
            "Persist Security Info=True;" +
            "User ID=sa;Password=Sql#123456789;" +
            "Encrypt=True;TrustServerCertificate=True;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Animal>(entity =>
        {
            entity.HasKey(e => e.IdAnimal);

            entity.ToTable("Animal");

            entity.Property(e => e.NombreAnimal)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Raza)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.RidTipoAnimal).HasColumnName("RIdTipoAnimal");

            entity.HasOne(d => d.RidTipoAnimalNavigation).WithMany(p => p.Animals)
                .HasForeignKey(d => d.RidTipoAnimal)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Animal_TipoAnimal");
        });

        modelBuilder.Entity<TipoAnimal>(entity =>
        {
            entity.HasKey(e => e.IdTipoAnimal);

            entity.ToTable("TipoAnimal");

            entity.Property(e => e.TipoDescripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}