// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebApp_MVC_Animales.Models;

public partial class Animal
{
    [Key]
    [Display(Name = "ID Animal")]
    public int IdAnimal { get; set; }

    [Required(ErrorMessage = "El nombre del animal es obligatorio.")]
    [StringLength(100, ErrorMessage = "El nombre no puede exceder los 100 caracteres.")]
    [Display(Name = "Nombre del Animal")]
    public string NombreAnimal { get; set; }

    //[Required(ErrorMessage = "El nombre dela raza es obligatorio.")]
    [StringLength(100, ErrorMessage = "El nombre no puede exceder los 100 caracteres.")]
    public string Raza { get; set; }

    // todo - anotation RidTipo
    [Display(Name = "ID Tipo de Animal")]
    public int RidTipoAnimal { get; set; }

    [DataType(DataType.Date)]
    [Display(Name = "Fecha de Nacimiento")]
    [Range(typeof(DateTime), "1/1/2000", "31/12/2100")]
    public DateOnly? FechaNacimiento { get; set; }

    //[JsonIgnore]
    public virtual TipoAnimal RidTipoAnimalNavigation { get; set; }

}