// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace WebApp_MVC_Animales.Models;

public partial class TipoAnimal
{
    public int IdTipoAnimal { get; set; }

    public string TipoDescripcion { get; set; }

    [JsonIgnore]
    public virtual ICollection<Animal> Animals { get; set; } = new List<Animal>();
}